const GET_COMMENTS = 'GET_COMMENTS';
const GET_COMMENTS_FULFILLED = 'GET_COMMENTS_FULFILLED';
const GET_COMMENTS_REJECTED = 'GET_COMMENTS_REJECTED';

const SAVE_COMMENT = 'SAVE_COMMENT';
const SAVE_COMMENT_FULFILLED = 'SAVE_COMMENT_FULFILLED';
const SAVE_COMMENT_REJECTED = 'SAVE_COMMENT_REJECTED';

export {
    GET_COMMENTS,
    GET_COMMENTS_FULFILLED,
    GET_COMMENTS_REJECTED,
    SAVE_COMMENT,
    SAVE_COMMENT_FULFILLED,
    SAVE_COMMENT_REJECTED,
};